name: Clippy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2
      - name: Build and run
        run: |
          echo 10 | make run
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: Format
        run: make format
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Run
        run: make run